# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cc74f45eced4d4662a7072faf8803b5a6ceb3b67eade2b00c18a77ce4568741df27feb9dac00c9be0cf0cb0c65bbf5ad314a4218b970614e759829dcde162ce

test:
  secret_key_base: e8f72a0b035f9c431ab5d3c3cad9f03b74e224a7b9e73554459cd984d9ccea8fefb261b95a844a4b19185474c6d33f204b0df599342a0e062ce4e549133fd882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
